#pragma once

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#undef POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define CIRQUE_PINNACLE_TAP_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2

#define OLED_IC OLED_IC_SH1107
#define OLED_UPDATE_INTERVAL 50
#define OLED_DISPLAY_128X128
#define USE_I2C
