#pragma once

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#undef POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2

#define OLED_DISPLAY_128X128
#define OLED_UPDATE_PROCESS_LIMIT 2
#define OLED_BRIGHTNESS 128
#define OLED_UPDATE_INTERVAL 50
#define OLED_TIMEOUT 0

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3
#define I2C1_CLOCK_SPEED 400000

#define QP_DC GP11
#define QP_CS GP12
#define QP_RESET GP13

#define SPLIT_LAYER_STATE_ENABLE
